import './components/search-bar.js'
import './components/article-result.js'
import './components/wiki-article.js'
import './components/test2.js'
import './components/view-index.js'
import './components/category-list.js'
import './components/wk-article.js'